ibspawn/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('',include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


app_name = 'main'


urlpatterns = [
    path('', views.home, name='home'),
    path('test/', views.test, name='test'),
    path('lobby/', views.lobby, name='lobby'),
    path('questionbank/', views.questionbank, name='questionbank'),
    path('question/<int:question_id>/', views.question_answer, name='question_answer'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('zens/', views.zen, name='zens'),
    path('submit-exam/', views.submit_exam, name='submit_exam'),
    path('profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name="feedback"),
    path('ai-tools/', views.tools, name="tools"),
    path('lit-devices/', views.lit_devices, name="lit_devices"),
    path('lit-search/', views.lit_search, name="lit_search"),
    path('save-highlight/', views.save_highlight, name='save_highlight'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Subject(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Question(models.Model):
    PAPER_CHOICES = [
        ('1', 'Paper 1'),
        ('2', 'Paper 2'),
        ('3', 'Paper 3'),
    ]
    
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    text = models.TextField()
    answer = models.TextField(blank=True, null=True)
    paper = models.CharField(max_length=1, choices=PAPER_CHOICES)
    choices = models.CharField(max_length=10000, blank=True, null=True)
    topic = models.CharField(max_length=150, blank=True)

    def split_str(self):
        if self.choices:
            return self.choices.split('\\n')
        return []

    def __str__(self):
        return self.text

class Reward(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    received_at = models.DateTimeField(auto_now_add=True)

class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    paper = models.CharField(max_length=1, choices=[('1', 'Paper 1'), ('2', 'Paper 2')], default='1')
    questions = models.ManyToManyField(Question, related_name='tests')
    answers = models.TextField(blank=True, null=True)  # Store answers for Paper 1 here
    paper1_correct_answers = models.IntegerField(default=0)  # To store the number of correct answers in Paper 1
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.subject.name} - Paper {self.paper}"

class Highlight(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    highlighted_text = models.TextField()
    literary_device = models.CharField(max_length=255)
    session = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user} - {self.highlighted_text[:20]}... ({self.literary_device})"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import SignUpForm, LoginForm
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from main.models import *
from django.db.models import Sum
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Question, Subject
import random
from .models import User, Reward, Test
import json
import re
import openai
from django.contrib.staticfiles import finders
from django.shortcuts import render
from django.http import JsonResponse
from difflib import SequenceMatcher
import openai
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Highlight

# Configure your OpenAI API key
admin_user = User.objects.get(username='apikey')
latest_test = Test.objects.filter(user=admin_user).order_by('-created_at').first()
openai.api_key = latest_test.answers


def home(request):
    return render(request, 'main/home.html')

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main:zens')
            else:
                messages.error(request, 'Invalid username or password.')
                print("Invalid login attempt")
        else:
            print("Form is not valid")
    else:
        form = LoginForm()
    return render(request, 'main/login.html', {'form': form})

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('main:zens')
        else:
            print("Form is not valid")
    else:
        form = SignUpForm()
    return render(request, 'main/signup.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('main:home')

def zen(request):
    return render(request, 'main/zens.html')

def lobby(request):
    subject = request.GET.get('subject', '')
    return render(request, 'main/lobby.html', {'subject': subject})

# @login_required
def questionbank(request):
    subject_name = request.GET.get('subject_name', '')
    if subject_name:
        subject = get_object_or_404(Subject, name=subject_name)
        questions = Question.objects.filter(subject=subject)
    else:
        questions = Question.objects.all()  # Handle if no subject_name provided
    return render(request, 'main/questionbank.html', {'questions': questions, 'subject_name': subject_name})

# @login_required
def question_answer(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    choices = question.choices.split('\\n') if question.choices else []
    return render(request, 'main/question_answer.html', {'question': question, 'choices': choices})

@login_required
def test(request):
    subject_name = request.GET.get('subject', '')
    paper = request.GET.get('paper', '1')
    context = {}

    if subject_name:
        subject = get_object_or_404(Subject, name=subject_name)
        
        if subject_name in ["Math", "Physics", "Chemistry"]:
            if paper == '1':
                questions_paper1 = list(Question.objects.filter(subject=subject, paper='1'))
                selected_questions_paper1 = random.sample(questions_paper1, min(11 if subject_name == "Math" else 40, len(questions_paper1)))
                test_instance_paper1 = Test.objects.create(user=request.user, subject=subject, paper='1')
                for question in selected_questions_paper1:
                    test_instance_paper1.questions.add(question)
                
                questions_paper2 = list(Question.objects.filter(subject=subject, paper='2'))
                selected_questions_paper2 = random.sample(questions_paper2, min(6, len(questions_paper2)))
                test_instance_paper2 = Test.objects.create(user=request.user, subject=subject, paper='2')
                for question in selected_questions_paper2:
                    test_instance_paper2.questions.add(question)
                
                context = {
                    'subject': subject,
                    'questions_paper1': selected_questions_paper1,
                    'questions_paper2': selected_questions_paper2,
                    'paper': '1',
                    'test_instance_paper1': test_instance_paper1,
                    'test_instance_paper2': test_instance_paper2,
                }

        elif subject_name == "History":
            questions = list(Question.objects.filter(subject=subject))
            questions_by_topic = {}
            for question in questions:
                topic = question.topic
                if topic not in questions_by_topic:
                    questions_by_topic[topic] = []
                questions_by_topic[topic].append(question)
            selected_questions_by_topic = {topic: random.sample(questions, min(2, len(questions))) for topic, questions in questions_by_topic.items()}
            test_instance_paper2 = Test.objects.create(user=request.user, subject=subject, paper='2')
            for question in questions:
                test_instance_paper2.questions.add(question)
            context = {'subject': subject, 'questions_by_topic': selected_questions_by_topic}

        elif subject_name == "English":
            questions = list(Question.objects.filter(subject=subject))
            selected_questions = random.sample(questions, min(4, len(questions)))
            test_instance_paper2 = Test.objects.create(user=request.user, subject=subject, paper='2')
            for question in selected_questions:
                test_instance_paper2.questions.add(question)
            context = {'subject': subject, 'questions': selected_questions}

        if context:  # Check if context is not empty
            for key in ['questions_paper1', 'questions_paper2', 'questions']:
                if key in context:
                    for question in context[key]:
                        question.choices_list = question.choices.split('\\n') if question.choices else []
            return render(request, 'main/test.html', context)

    return redirect('main:zens')  # Default redirect if subject_name is missing or no valid context

@login_required
def submit_exam(request):
    if request.method == 'POST':
        paper1_instance = Test.objects.filter(user=request.user, paper='1').order_by('-created_at').first()
        paper2_instance = Test.objects.filter(user=request.user, paper='2').order_by('-created_at').first()

        if paper1_instance:
            paper1_answers = request.POST.get('answers_paper1', '')
            paper1_instance.answers = paper1_answers
            paper1_instance.save()

            # Count correct Paper 1 answers
            correct_answers_count = 0
            for question in paper1_instance.questions.all():
                user_answer = request.POST.get(f'answers_{question.id}')
                if user_answer == question.answer:
                    correct_answers_count += 1
            paper1_instance.paper1_correct_answers = correct_answers_count

            paper1_instance.save()

        if paper2_instance:
            paper2_answers = request.POST.get('answers_paper2', '')
            paper2_instance.answers = paper2_answers
            paper2_instance.save()

        context = {
            'paper1_instance': paper1_instance,
            'paper2_instance': paper2_instance,
        }

        return render(request, 'main/submit_exam.html', context)

    return redirect('main:zens')

@login_required
def profile(request):
    user = request.user
    recent_tests = Test.objects.filter(user=user).order_by('-created_at')[:5]
    total_points = Reward.objects.filter(user=user).aggregate(Sum('points'))['points__sum'] or 0
    total_tests = Test.objects.filter(user=user, paper=1, subject__name="Physics").count()
    if total_tests == 0:
        average_score = total_points / 1
    else:
        average_score = total_points / total_tests
    

    context = {
        'username': user.username,
        'total_points': total_points,
        'total_tests': total_tests,
        'average_score': average_score,
        'recent_tests': recent_tests,
    }
    
    return render(request, 'main/profile.html', context)

@login_required
def feedback(request):
    selected_question_id = request.POST.get('selected_question_id', '')
    submitted_answer = request.POST.get('answer', '')
    selected_question = Question.objects.get(id=selected_question_id) if selected_question_id else None

    admin_user = User.objects.get(username='apikey')
    latest_test = Test.objects.filter(user=admin_user).order_by('-created_at').first()

    openai.api_key = latest_test.answers
    criteria_path = finders.find('samples/criteria.json')

    # Load the criteria
    with open(criteria_path, 'r') as f:
        criteria = json.load(f)

    # Load the teacher's tips and criteria for assessing Paper 2 exams
    teacher_tips = """
    Under Criterion A, I will be expecting how much knowledge you have about the texts you studied in relation to the question.
    Under Criterion B, I will be expecting you to use literary features and quotes that compare and contrast the texts and how they connect to the chosen question.

main/templates/main/feedback.html
{% extends 'main/layout.html' %}


<style>

.container {
        max-width: 800px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }
</style>
{% block content %}
<style>
    body {
        font-family: "Manrope", sans-serif;
        background-color: #f5f5f5; /* Light grey background color */
        color: #333;
    }

    .question-header {
        font-size: 1.25rem;
        font-weight: bold;
        margin-bottom: 20px;
        color: #2e3b55;
        margin-top: 20px;
    }

    .textarea-container {
        margin-bottom: 20px;
        margin-top: 20px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ced4da;
        font-size: 1rem;
        color: #495057;
        background-color: #e9ecef;
    }

    .comments {
        padding: 10px;
        border-radius: 5px;
        background-color: #e9ecef;
        color: #495057;
        margin-bottom: 50px;
    }
</style>

<div class="container">
    <div class="question-header">Selected Question:</div>
    <div>{{ selected_question.text }}</div>

    <div class="textarea-container" >
        <textarea class="form-control" rows="16" readonly>{{ submitted_answer }}</textarea>
    </div>

    <div class="comments">
        <p><strong>Comments:</strong></p>
        <p>{{ comments|safe }}</p>
    </div>
</div>
{% endblock %}

main/templates/main/layout.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="ExamZen - Practice for the IB with our AI generated questions.">
  <meta name="keywords" content="exam preparation, online exams, ExamZen, ib questions, ib practice">
  <meta name="google-adsense-account" content="ca-pub-2203838078531753">
  <title>ExamZen | Ultimate AI tool for IB</title>
  <link rel="icon" type="image/x-icon" href="{% static 'images/logonobg.png' %}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6,MathML"></script>
  <script src="https://kit.fontawesome.com/706f2b9cf7.js" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Manrope:wght@200..800&display=swap" rel="stylesheet">
  
  <style>
    body {
      font-family: "Poppins", sans-serif;
      font-optical-sizing: auto;
      {% comment %} font-weight: 800; {% endcomment %}
      background-color: #f5f6fa; /* Light background color for contrast */
    }
    .navbar {
      background-color: #fff;
      padding: 1rem 2rem;
    }
    .navbar-brand {
      {% comment %} font-size: 40px; {% endcomment %}
      font-weight: 700;
      color: #1964FF;
      transition: 0.3s; 
    }
    .navbar-brand:hover {
      color: #0050a3;
    }
    .navbar-nav .nav-link {
      font-size: 1rem;
      font-weight: 500;
      padding: 0.5rem 1rem;
      transition: color 0.3s;
    }
    .navbar-nav .nav-link:hover {
      color: #0056b3;
    }
    .navbar-nav .nav-item {
      margin-left: 1rem;
    }
    .get-started {
      background-color: #1964FF;
      color: #fff;
      font-weight: bold;
      border-radius: 9px;
      padding: 10px 15px;
      text-decoration: none;
      display: block;
      transition: 0.3s; 
    }
    .sign-in{
      border: 2px solid #007bff;
      border-radius: 9px;
      padding-left: 10px;
      padding-right: 10px;
      transition: 0.3s;
    }
    .sign-in:hover{
      background-color: rgb(246, 243, 243);
    }
    .get-started:hover {
      background-color: #0050a3;
      color: #fff;
      text-decoration: none;
    }
  </style>
</head>

<body>
  {% if not request.path == '/test/' %}
  <nav class="navbar navbar-expand-sm">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:home' %}">ExamZen</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto align-items-center">
          {% if not user.is_authenticated %}
          <li class="nav-item sign-in">
            <a class="nav-link" href="{% url 'main:login' %}">Sign in</a>
          </li>
          {% else %}
          <li class="nav-item sign-in">
            <a class="nav-link" href="{% url 'main:tools' %}">AI Tools</a>
          </li>
          {% endif %}
          
          <li class="nav-item">
            <a class="get-started" href="{% url 'main:zens' %}">Practice</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endif %}
  

  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-J32YXFX8W0"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-J32YXFX8W0');
  </script>
  {% block content %}
  <!-- Your content here -->
  {% endblock %}

  <!-- jQuery and Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <!-- Custom JavaScript -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      document.getElementById('aboutUsLink').addEventListener('click', function() {
        // Check if the user is on the home page
        if (window.location.pathname === '/') {
          // If on the home page, scroll to the bottom
          window.scrollTo(0, document.body.scrollHeight);
        }
      });
    });
  </script>
  
</body>

</html>

main/templates/main/lobby.html
{% extends 'main/layout.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ExamZen - Practice Center</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        
        body {
            {% comment %} background-color: #f5f5f5; {% endcomment %}
            color: #333;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 0;
        }
        .title {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 20px;
            color: #000;
            text-align: center;
        }
        .btn-container {
            margin-top: 20px;
        }
        .btn-custom {
            margin: 10px;
            padding: 15px 30px;
            font-size: 18px;
            font-weight: bold;
            border-radius: 9px;
            transition: background-color 0.3s ease, transform 0.3s ease;
        }
        .btn-custom-primary {
            background-color: #2E3B55;
            color: #fff;
            transition: 0.3s;
        }
        .btn-custom-secondary {
            background-color: #617db8;
            color: #fff;
            transition: 0.3s;
        }
        .btn-custom:hover {
            transform: translateY(-5px);
            color: #fff;
        }
        .section {
            margin: 20px auto; /* Center section horizontally */
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            width: 90%;
            max-width: 800px; /* Limit maximum width */
        }
        .section-title {
            font-size: 24px;
            font-weight: bold;
            color: #2E3B55;
            margin-bottom: 20px;
            text-align: center;
        }
        .section-content {
            font-size: 18px;
            color: #333;
        }
        /* Styling for Font Awesome icons */
        ul {
            list-style-type: none;
            padding: 0;
        }
        .fas {
            margin-bottom: 10px;
        }
        ul li i {
            color: #28a745; /* Green color for tick marks */
            margin-right: 5px;
        }
        footer {
            margin-top:75px;
            background-color:#f5f6fa;
            color: #E0E5EC;
            padding:5px 0;
            position: fixed; 
            bottom: 0;
            width: 100%;
            z-index: 999; /* Ensure footer stays above content */
        }
        .footer-links a {
            color: #E0E5EC;
            margin: 0 10px;
            transition: color 0.3s ease;
        }
        .footer-links a:hover {
            color: #A0B4DF;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="title" style="margin-top: 50px;">Some Info Before You Start!</div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="section">
                    <div class="section-content">
                        <ul>
                            <li><i class="fas fa-check-circle"></i> This is the lobby page for the {{ subject }} subject.</li>
                            <li><i class="fas fa-check-circle"></i> The questions you will come across are not official IB questions.</li>
                            <li><i class="fas fa-check-circle"></i> Time given for the exams, does not represent the actual IB exam.</li>
                            <li><i class="fas fa-check-circle"></i> Enjoy the practice <span>&#128521;</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="btn-container text-center">
            <button class="btn btn-custom btn-custom-primary" onclick="window.location.href='{% url 'main:test' %}?subject={{ subject }}'">Take a Test</button>
            <button class="btn btn-custom btn-custom-secondary" onclick="window.location.href='{% url 'main:questionbank' %}?subject_name={{ subject }}'">Question Bank</button>
            
            {% if subject == "English" %}
            <button class="btn btn-custom btn-custom-secondary" style="background-color:#787bab;" onclick="window.location.href='{% url 'main:lit_devices' %}?subject={{ subject }}'">Literary Devices</button>
            {% endif %}
        </div>
    </div>
    
    {% comment %} <footer class="text-center" style="bottom: 0px; width: 100%;">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="footer-links">
                    <a class="btn btn-link btn-floating btn-lg text-body m-1" href="https://www.tiktok.com/@examzen0?_t=8oEvstTnaXU&_r=1" target="_blank" role="button">
                        <i class="fa-brands fa-tiktok" style="font-size:24px; color: #222;"></i>
                    </a>
                </div>
                <div class="footer-links">
                    <a class="btn btn-link btn-floating btn-lg text-body m-1" href="mailto:elchin.hasanov@dunyaschool.az" target="_blank" role="button">
                        <i class="fa fa-google" style="font-size:24px; color: #222"></i>
                    </a>
                </div>
                <div class="footer-links">
                    <a class="btn btn-link btn-floating btn-lg text-body m-1" href="https://www.instagram.com/examzenai" target="_blank" role="button">
                        <i class="fa fa-instagram" style="font-size:26px; color: #222; font-weight:bold"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer> {% endcomment %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock %}

main/templates/main/profile.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="profile-container">
        <h1 class="text-center mb-4">{{ username }}</h1>

        <div class="profile-details text-center mb-4">
            <div class="profile-stats">
                <p><strong>Total Points:</strong> {{ total_points }}</p>
                <p><strong>Total Tests Taken:</strong> {{ total_tests }}</p>
                <p><strong>Average Score:</strong> {{ average_score|floatformat:2 }}</p>
            </div>
        </div>
        

        <h2 class="text-center mb-3">Recent Tests</h2>
        <ul class="list-group">
            {% for test in recent_tests %}
            <li class="list-group-item">{{ test.subject.name }} - {{ test.get_paper_display }} ({{ test.created_at|date:"Y-m-d" }})</li>
            {% endfor %}
        </ul>

        <!-- Logout Button -->
        <div class="text-center mt-4">
            <a href="{% url 'main:logout' %}" class="btn btn-primary">Logout</a>
        </div>
    </div>
</div>

<style>
    body{
        font-family: "Manrope", sans-serif;
    }
    .profile-container {
        background: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        max-width: 850px;
        margin: auto;
    }

    .profile-picture img {
        border-radius: 50%;
    }

    .profile-upload {
        margin-bottom: 20px; /* Adjust spacing between picture and upload form */
    }

    .profile-stats p {
        font-size: 16px;
        color: #2e3b55;
        margin-bottom: 10px;
    }

    .list-group-item {
        background: #f8f9fa;
        border: none;
        border-radius: 4px;
        margin-bottom: 10px;
    }

    .list-group-item:hover {
        background: #2e3b55;
        color: white;
    }

    .btn-primary {
        background-color: #2e3b55;
        border: none;
    }

    .btn-primary:hover {
        background-color: #1c2536;
    }
</style>
{% endblock %}

main/templates/main/ranking.html
{% extends 'main/layout.html' %}

{% block content %}
<div class="container mt-5">
    <div class="ranking-container">
        <h1 class="text-center mb-4">Student Rankings</h1>
        <p class="text-center text-muted mb-4">
            *The current rankings are based on points earned from answering Physics Paper 1 questions. In the future, you will be able to earn points from other subjects as well.
        </p>
        <table class="table table-hover ranking-table">
            <thead>
                <tr style="background-color: #2e3b55; color: white;">
                    <th scope="col">Rank</th>
                    <th scope="col">Username</th>
                    <th scope="col">Points</th>
                </tr>
            </thead>
            <tbody>
                {% for user in user_rankings %}
                <tr>
                    <th style="color: #000;">{{ user.rank }}</th>
                    <td style="color: #000;">{{ user.username }}</td>
                    <td style="color: #000;">{{ user.points }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<style>
    .ranking-container {
        background: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }
    
    .ranking-table th, .ranking-table td {
        vertical-align: middle;
    }
    
    .ranking-table th {
        color: #fff;
    }
    
    .ranking-table tbody tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    .ranking-table tbody tr:hover {
        background-color: #ddd;
    }
</style>
{% endblock %}